version: "3.8"
services:
  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_DB: rtchat
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
